### ISSUE TITLE
Implement automated testing: Unit, widget and integration

### ISSUE THREAD

**Issue by JohnPalmer** [ActivitySpaceProject/space_mapper#39]
Automated tests to implement:
- [x] Unit testing for the custom classes and functions
- [ ] Widget testing for all the screens
- [ ] Integration testing

**Comment by pablogalve** [comment]
@JohnPalmer I've updated your comment to subdivide this task in 3 and make it more clear.

At this moment, all the types of tests can be performed. This issue [#42 [Translation bug] Null check operator used on a null value](https://github.com/ActivitySpaceProject/space_mapper/issues/42) took me some days to figure out and it's the reason that many tests kept failing. But now that I solved it on the latest commit, the tests are looking great. Especially the integration tests are very promising.

Integration tests are slow but very reliable tests that can be performed on physical devices or OS emulator. Meaning that we can test the app on multiple emulators and get performance reviews, even if we don't have it physically. Once we have a good amount of test coverage in the following weeks I'll see if we can integrate it into our CI (so those integration tests are automatically run on x event, same as unit/widget tests do)

I think this will be a game changer in terms of security, especially for apps with multiple contributors such as MAlert where there are lots of users and errors can be expensive.
